dist:     trusty
sudo:     required

language: c

os:
  - linux

compiler:
  - gcc

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - sudo apt-get install cppcheck
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev valgrind cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - which valgrind
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cppcheck console_communication.c console_communication.h consistent/consistent_realization.c consistent/consistent_realization.h Google_tests/tests.cpp consistent/consistent_realization.h parallel/parallel_realization.c
  - mkdir build
  - cd build
  - ls
  - cmake ../
  - ls Google_tests
  - cd ../Google_tests
  - ls
  - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes chmod a+x ./tests.cpp
  - chmod a+x ./tests.cpp
  - sudo apt-get install -y gcovr
  - gcovr -r .
